### PR TITLE
Readme release

### PR DESCRIPTION
**Pull request by egouldo**
Hi @Doi90 please have a look through the latest version of the README and let me know if you're happy with it /whether I've missed anything important.

Also, I had some massive merge-conflicts unfortunately, so please let me know if this messes with your latest repo-port and BFG @psychtek .

-- Elliot.

### CODE REVIEW

**Review by psychtek — APPROVED** [review]

**Comment by psychtek** [comment]
I feel like when I ran the BFG it was done before I did some house keeping and fixed the errors that are appearing in the check - mostly from data objects we ported over. @egouldo you want me to rebase on this branch and fix the conflicts?

**Comment by egouldo** [comment]
> I feel like when I ran the BFG it was done before I did some house keeping and fixed the errors that are appearing in the check - mostly from data objects we ported over. @egouldo you want me to rebase on this branch and fix the conflicts?

Yes please @psychtek !!

**Comment by psychtek** [comment]
@egouldo not a prob I'll jump into that now. Pretty sure they are the same conflicts so should be straight forward fix.

**Comment by egouldo** [comment]
> @egouldo not a prob I'll jump into that now. Pretty sure they are the same conflicts so should be straight forward fix.

Excellent thanks, the only thing that we'll have to be careful about is keeping the version of the README and a couple additional images files that will be on this branch. Otherwise everything else can be rebased on master.

**Comment by psychtek** [comment]
@egouldo ok so should be good! Will have todo some house keeping after this is pushed into master so we have a working clean master branch to work off

**Pull request merged**
