### PR TITLE
Update manuscript to reference correct object names and paper_id

### PR DESCRIPTION
**Pull request by egouldo**
- Manuscript has been updated to reference the anonymised paper ID's and names to old supp. data objects have been changed to reflect current names.
- Manuscript files moved to `./vignettes/`, BUT, I can't get the vignette to register when calling `browseVignettes(package = "aggreCAT")`. @psychtek  can you please make any necessary changes to the draft PR so the vignette is included in the package build?

### CODE REVIEW

**Comment by psychtek** [comment]
@egouldo No worries ill jump in and get this branch rolling 🥼

**Comment by psychtek** [comment]
Ok so I am getting conflicting information when I start digging around as to where to put manuscript docs. Seems that the vignettes is for package [reference vignettes](https://stackoverflow.com/questions/69570632/is-there-a-special-rmd-template-to-create-r-package-vignette-in-pdf)? Manuscripts go into sub folder in `inst/docs`. Confused 😅 
https://stackoverflow.com/questions/59645828/how-to-properly-organise-vignettes-and-inst-folders-when-creating-new-r-package

We might need to create a [reference](https://stackoverflow.com/questions/16986422/r-create-reference-manual-with-r-cmd-check?noredirect=1&lq=1) pdf of the package anyway? 

My understanding is that we create the rmd in the vignettes folder. 
then `devtools::build_vignettes()` which does a bunch of fancy stuff: 
```r
ℹ Copying vignettes
ℹ Moving manuscript.html and manuscript.R to doc/
ℹ Copying manuscript.Rmd to doc/
ℹ Building vignette index
```
But this is for html. 

@egouldo  But the manuscript is printing to pdf and html correct? 

If all we need is the pdf then theres info [here](https://cran.r-project.org/web/packages/R.rsp/vignettes/R_packages-Static_PDF_and_HTML_vignettes.pdf) about just placing the pdf and asis inside the vignettes. 

Also, unless theres a more up to date link Quarto isnt currently supported for vignettes (at least for CRAN approval): https://github.com/r-lib/pkgdown/issues/2154 
https://github.com/EMODnet/EMODnetWCS/issues/11
So we might need to change it back to `Rmd` format. 

Good summary about [vignettes and pdf articles here](https://blog.r-hub.io/2020/06/03/vignettes/)

**Comment by egouldo** [comment]
Hmmm, sounds like there's also a difference between 'reference manual' and a 'vignette'. I think reference manual is cobbled together document of all the R man for the package, and vignette is a separate long-form document yet again.

**Comment by egouldo** [comment]
For now, simplest way forward is to include the knitted quarto PDF of the manuscript rather than trying to build the .qmd document in the package building workflow.

See: https://cran.r-project.org/web/packages/R.rsp/vignettes/R_packages-Static_PDF_and_HTML_vignettes.pdf

- [ ] Elliot to include PDF of manuscript as PDF

**Comment by egouldo** [comment]
Ok @psychtek , so package builds locally, but fails check because `r.sp` is not specified as the package builder (had to change it from `knitr` to `r.sp` (See [9a79e4f](https://github.com/metamelb-repliCATS/aggreCAT/pull/11/commits/9a79e4f27bc088b4c335a6a7ccebb21a20b84078), file: DESCRIPTION). That's the vignette builder we need to include PDF as pkg vignette.

Log L#30: https://github.com/metamelb-repliCATS/aggreCAT/runs/8199741340?check_suite_focus=true#step:5:31

**Comment by psychtek** [comment]
Creeping every so closely 😄

**Comment by egouldo** [comment]
> Creeping every so closely 😄

😅 Do we need to update GH actions file or docker to make the checks work?

**Comment by psychtek** [comment]
Nah its neeeearly there! I have set it up to flag when warnings are present
```bash
checking for portable file names ... WARNING
  Found the following files with non-portable file names:
    inst/ms/_extensions/jss/_extensions/quarto-ext/fancy-text/_extension 2.yml
    inst/ms/_extensions/jss/_extensions/quarto-ext/fancy-text/fancy-text 2.lua
```
if these arent needed for ms build then add to .buildignore ?

**Comment by egouldo** [comment]
ping @psychtek ready for review, we all ✅ on Rcmdcheck

**Review by psychtek — COMMENTED** [review]
```yaml
      - name: vignette-builder
        run:  install.packages("R.rsp"); remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
```
Ill bake this into the image at a later date.

**Comment by egouldo** [comment]
Also adding this reference to the mix here:
- https://www.jstatsoft.org/style - how to incorporate JSS manuscript as vignette in package

I’ll have a look at those other refs shortly.

Sent from my iPhone

On 6 Sep 2022, at 10:58 am, Aaron ***@***.***> wrote:

﻿

Ok so I am getting conflicting information when I start digging around as to where to put manuscript docs. Seems that the vignettes is for package reference vignettes<https://stackoverflow.com/questions/69570632/is-there-a-special-rmd-template-to-create-r-package-vignette-in-pdf>? Manuscripts go into sub folder in inst/docs. Confused 😅
https://stackoverflow.com/questions/59645828/how-to-properly-organise-vignettes-and-inst-folders-when-creating-new-r-package<https://stackoverflow.com/questions/59645828/how-to-properly-organise-vignettes-and-inst-folders-when-creating-new-r-package>

We might need to create a reference<https://stackoverflow.com/questions/16986422/r-create-reference-manual-with-r-cmd-check?noredirect=1&lq=1> pdf of the package anyway?

My understanding is that we create the rmd in the vignettes folder.
then devtools::build_vignettes() which does a bunch of fancy stuff:

ℹ Copying vignettes
ℹ Moving manuscript.html and manuscript.R to doc/
ℹ Copying manuscript.Rmd to doc/
ℹ Building vignette index

But this is for html.

@egouldo<https://github.com/egouldo> But the manuscript is printing to pdf and html correct?

If all we need is the pdf then theres info here<https://cran.r-project.org/web/packages/R.rsp/vignettes/R_packages-Static_PDF_and_HTML_vignettes.pdf> about just placing the pdf and asis inside the vignettes.

Also, unless theres a more up to date link Quarto isnt currently supported for vignettes (at least for CRAN approval): r-lib/pkgdown#2154<https://github.com/r-lib/pkgdown/issues/2154>
EMODnet/EMODnetWCS#11<https://github.com/EMODnet/EMODnetWCS/issues/11>
So we might need to change it back to Rmd format.

Good summary about vignettes and pdf articles here<https://blog.r-hub.io/2020/06/03/vignettes>

**Pull request merged**
